spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/nileshmkjee123/configurations.git"
          default-label: main #this signifies the branch
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"